name: Test yaml

on:
  - push:
      branches: [main]
  - pull_request:
  - workflow_dispatch:

jobs:
  test-yaml:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      with:
        python-version: 3.8
      uses: actions/setup-python@v5
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Test yaml
      run: |
        _test/test_yaml.py
